using System.Collections;
using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using AcademicJudge.Generator.Models;

namespace AcademicJudge.Generator.Services;

public class CodeEmitter
{
    public string Emit(TaskConfig config)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated automatically by AcademicJudge.Generator />");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
        sb.AppendLine("using AcademicJudge.Attributes;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.TargetNamespace};");
        sb.AppendLine();
        sb.AppendLine("[TestClass]");
        sb.AppendLine($"public class {config.TaskName}");
        sb.AppendLine("{");

        foreach (var testCase in config.TestCases)
        {
            EmitTestCase(sb, config, testCase);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private void EmitTestCase(StringBuilder sb, TaskConfig config, TestCaseConfig testCase)
    {
        int timeLimit = testCase.CustomTimeLimitMs ?? 1000;

        sb.AppendLine($"    [AcademicTestMethod(TimeLimitMs = {timeLimit}, IsHidden = {testCase.IsHidden.ToString().ToLower()})]");
        sb.AppendLine($"    [Points({testCase.Points})]");

        if (testCase.MaxOperations.HasValue)
        {
            sb.AppendLine($"    [NumberOfOperations({testCase.MaxOperations.Value})]");
        }

        sb.AppendLine($"    public void {testCase.Name}()");
        sb.AppendLine("    {");
        string inputLiteral = FormatLiteral(testCase.Input);
        string expectedLiteral = FormatLiteral(testCase.ExpectedOutput);

        sb.AppendLine($"        // Arrange");
        sb.AppendLine($"        var input = {inputLiteral};");
        sb.AppendLine($"        var expectedOutput = {expectedLiteral};");
        sb.AppendLine($"        var studentSolution = new {config.StudentClassName}();");
        sb.AppendLine();
        sb.AppendLine($"        var actualOutput = studentSolution.{config.MethodName}(input);");
        sb.AppendLine();
        sb.AppendLine("         // Assert");
        sb.AppendLine($"        Assert.AreEqual(expectedOutput, actualOutput);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private string FormatLiteral(object? value)
    {
        if (value is null) return "null";

        if (value is JsonElement element)
        {
            return FormatJsonElement(element);
        }

        if (value is JsonNode node)
        {
            using JsonDocument doc = JsonDocument.Parse(node.ToJsonString());
            return FormatJsonElement(doc.RootElement);
        }

        if (value is string str) return $"\"{EscapeString(str)}\"";
        if (value is bool b) return b ? "true" : "false";
        if (value is int || value is long || value is short || value is byte) return value.ToString()!;
        if (value is double d) return $"{d.ToString(CultureInfo.InvariantCulture)}d";
        if (value is float f) return $"{f.ToString(CultureInfo.InvariantCulture)}f";
        if (value is decimal dec) return $"{dec.ToString(CultureInfo.InvariantCulture)}m";

        if (value is IEnumerable enumerable)
        {
            var items = new List<string>();
            foreach (var item in enumerable)
            {
                items.Add(FormatLiteral(item));
            }

            var type = value.GetType();
            if (type.IsArray)
            {
                string elementType = type.GetElementType()?.Name ?? "var";
                return $"new {elementType}[] {{ {string.Join(", ", items)} }}";
            }

            return $"new[] {{ {string.Join(", ", items)} }}";
        }

        string json = JsonSerializer.Serialize(value);
        string escapedJson = json.Replace("\"", "\"\"");
        string typeName = value.GetType().FullName ?? "object";

        return $"System.Text.Json.JsonSerializer.Deserialize<{typeName}>(@\"{escapedJson}\")!";
    }

    private string FormatJsonElement(JsonElement element)
    {
        switch (element.ValueKind)
        {
            case JsonValueKind.String:
                return $"\"{EscapeString(element.GetString() ?? string.Empty)}\"";

            case JsonValueKind.Number:
                return element.GetRawText();

            case JsonValueKind.True:
                return "true";

            case JsonValueKind.False:
                return "false";

            case JsonValueKind.Null:
            case JsonValueKind.Undefined:
                return "null";

            case JsonValueKind.Array:
                var items = new List<string>();
                foreach (var item in element.EnumerateArray())
                {
                    items.Add(FormatJsonElement(item));
                }
                return $"new[] {{ {string.Join(", ", items)} }}";

            case JsonValueKind.Object:
            default:
                string rawJson = element.GetRawText().Replace("\"", "\"\"");
                return $"System.Text.Json.JsonSerializer.Deserialize<object>(@\"{rawJson}\")!";
        }
    }

    private string EscapeString(string input)
    {
        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}