using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using AcademicJudge.Generator.Models;

namespace AcademicJudge.Generator.Services;

public class CodeEmitter
{
    public string Emit(TaskConfig config)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated automatically by AcademicJudge.Generator />");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.VisualStudio.TestTools.UnitTesting;");
        sb.AppendLine("using AcademicJudge.Attributes;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.TargetNamespace};");
        sb.AppendLine();
        sb.AppendLine("[TestClass]");
        sb.AppendLine($"public class {config.TaskName}");
        sb.AppendLine("{");

        foreach (var testCase in config.TestCases)
        {
            EmitTestCase(sb, config, testCase);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private void EmitTestCase(StringBuilder sb, TaskConfig config, TestCaseConfig testCase)
    {
        int timeLimit = testCase.CustomTimeLimitMs ?? 1000;

        sb.AppendLine(
            $"    [AcademicTestMethod(TimeLimitMs = {timeLimit}, IsHidden = {testCase.IsHidden.ToString().ToLower()})]");
        sb.AppendLine($"    [Points({testCase.Points})]");

        if (testCase.MaxOperations.HasValue)
        {
            sb.AppendLine($"    [NumberOfOperations({testCase.MaxOperations.Value})]");
        }

        sb.AppendLine($"    public void {testCase.Name}()");
        sb.AppendLine("    {");
        string inputLiteral = FormatLiteral(testCase.Input);
        string expectedLiteral = FormatLiteral(testCase.ExpectedOutput);

        sb.AppendLine($"        // Arrange");
        sb.AppendLine($"        var input = {inputLiteral};");
        sb.AppendLine($"        var expectedOutput = {expectedLiteral};");
        sb.AppendLine($"        var studentSolution = new {config.StudentClassName}();");
        sb.AppendLine();
        sb.AppendLine($"        var actualOutput = studentSolution.{config.MethodName}(input);");
        sb.AppendLine();
        sb.AppendLine("         // Assert");
        sb.AppendLine($"        Assert.AreEqual(expectedOutput, actualOutput);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private string FormatLiteral(object? value)
    {
        if (value is null) return "null";

        if (value is JsonElement element)
        {
            switch (element.ValueKind)
            {
                case JsonValueKind.Array:
                    var items = new List<string>();
                    foreach (var item in element.EnumerateArray())
                    {
                        items.Add(FormatLiteral(item));
                    }
                    return $"new[] {{ {string.Join(", ", items)} }}";

                case JsonValueKind.String:
                    return $"\"{element.GetString()}\"";

                case JsonValueKind.Number:
                    return element.GetRawText();

                case JsonValueKind.True:
                    return "true";

                case JsonValueKind.False:
                    return "false";

                case JsonValueKind.Null:
                case JsonValueKind.Undefined:
                    return "null";

                default:
                    return element.GetRawText();
            }
        }

        if (value is string str)
        {
            return $"\"{str}\"";
        }

        if (value is bool b)
        {
            return b ? "true" : "false";
        }

        return JsonSerializer.Serialize(value);
    }
}