// <auto-generated />
// Generated automatically by AcademicJudge.Generator />
// </auto-generated>

using Microsoft.VisualStudio.TestTools.UnitTesting;
using AcademicJudge.Attributes;

namespace AcademicJudge.Tests;

[TestClass]
public class GeneratedFactorialTests
{
    [AcademicTestMethod(TimeLimitMs = 1000, IsHidden = false)]
    [Points(2)]
    public void Test_Factorial_Zero()
    {
        // Arrange
        var input = 0;
        var expectedOutput = 1;
        var studentSolution = new StudentSolution();

        var actualOutput = studentSolution.Solve(input);

         // Assert
        Assert.AreEqual(expectedOutput, actualOutput);
    }

    [AcademicTestMethod(TimeLimitMs = 1000, IsHidden = false)]
    [Points(5)]
    public void Test_Factorial_Five()
    {
        // Arrange
        var input = 5;
        var expectedOutput = 120;
        var studentSolution = new StudentSolution();

        var actualOutput = studentSolution.Solve(input);

         // Assert
        Assert.AreEqual(expectedOutput, actualOutput);
    }

    [AcademicTestMethod(TimeLimitMs = 1000, IsHidden = false)]
    [Points(5)]
    public void Test_Factorial_Seven()
    {
        // Arrange
        var input = 7;
        var expectedOutput = 5040;
        var studentSolution = new StudentSolution();

        var actualOutput = studentSolution.Solve(input);

         // Assert
        Assert.AreEqual(expectedOutput, actualOutput);
    }

}
