// <auto-generated />
// Generated automatically by AcademicJudge.Generator />
// </auto-generated>

using Microsoft.VisualStudio.TestTools.UnitTesting;
using AcademicJudge.Attributes;

namespace AcademicJudge.Tests;

[TestClass]
public class Task01Tests
{
    [AcademicTestMethod(TimeLimitMs = 300, IsHidden = false)]
    [Points(5)]
    public void Test_SumArray_Basic()
    {
        // Arrange
        var input = new[] { 1, 2, 3, 4 };
        var expectedOutput = 10;
        var studentSolution = new StudentSolution();

        var actualOutput = studentSolution.Solve(input);

         // Assert
        Assert.AreEqual(expectedOutput, actualOutput);
    }

    [AcademicTestMethod(TimeLimitMs = 100, IsHidden = true)]
    [Points(2)]
    public void Test_SumArray_Zeros()
    {
        // Arrange
        var input = new[] { 0, 0, 0 };
        var expectedOutput = 0;
        var studentSolution = new StudentSolution();

        var actualOutput = studentSolution.Solve(input);

         // Assert
        Assert.AreEqual(expectedOutput, actualOutput);
    }

    [AcademicTestMethod(TimeLimitMs = 100, IsHidden = true)]
    [Points(1)]
    public void Kornel_test()
    {
        // Arrange
        var input = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
        var expectedOutput = 45;
        var studentSolution = new StudentSolution();

        var actualOutput = studentSolution.Solve(input);

         // Assert
        Assert.AreEqual(expectedOutput, actualOutput);
    }

}
